spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leese?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Hong_Kong
    username: root
    password:


  application:
    name: user-center

  # session 超时时间 (秒)
  session:
    timeout: 86400

mybatis-plus:
  # 指定 Mapper XML 路徑，根據你的實際目錄修改
  mapper-locations: classpath*:generator/mapper/*.xml
  type-aliases-package: com.leese.usercenter.model.entity

  configuration:
    # 是否開啟駝峰轉換 (false 表示關閉)
    map-underscore-to-camel-case: false

  global-config:
    db-config:
      logic-delete-field: isDelete        # 全局邏輯刪除字段名
      logic-delete-value: 1               # 邏輯已刪除值
      logic-not-delete-value: 0           # 邏輯未刪除值

alipay:
  app-id: 9021000162625441
  private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCA3vbQqyqKSxZ2ZIUGgXaYFJ8p7DMien1fccTOHAjtgZc+KxNRSuabpsirLpe0HtZUivs6QHtOnuOG+8wiQAsu/AtqcvqHnoNvq8BLIQ0tKiWjNSpIpz0jK27oUGaJGym0WhEN4pox+m8qt/3TCWbCAoyR2TdNiVqSu7u0X3A8VB4UP8/uInN+/fLkbeuLHL3P5epH/aH/jiGMAMFee6epuV50tz0ICNe2fcvz6bvl7ptRwYLa3+eOxKVSq/qxU2VHxLJxr1IL5tHqsadzhO31wgFVrCnXKjHWn63P6zNsQa1/8oCziryX/77mTQvDX9Sra6hpoyszdz9UcVFKrAk7AgMBAAECggEAQEDrBreRCkrN9FHCEbBTFRiTEy/1fudbw07SNYG84c6PPiv0AcA6orjRrKgac3A8pQJ2qGCmGlkWUKMS8LDF4rNAbd7OEvhxyCf2RH9CNpahFXLYlkjsLrDlJ2eO+CVW8dlGT4oAH5MiAkaig6pYVbs3ozCOZlZplmeL+y7qoukGhRB/4o0XaRlfAdkR3LMcPsIXAa0MiCP/iSJHorsQdSPoCVs3QeufLrG298PgqKT/aXlGfoSDv4+G7vtBn2V591qZVhgEaEUltXFIRegxc2K7tLh6XxB9ZhzUVcj3NyDcTZWWFBsYszxQ8zDT2/rjFj6OG42QkNfPKQXbA4dGwQKBgQDUpoAz9IFymIpFa58PqbNNFmIB2soyMn2TzeZxhXy1rBvkcOU/l1Gky0iWDI7GCwxzLtn+S9oNeiqYzfroxUEnctt05SvYUGd+U/eeAVruYbHvRtl3EAKyu+n5WfvkVBoCmCgSgaZ1EAkg7lTi+Z5VTELn+kNnOp2hHDAQszWkMwKBgQCbJEzHitdsFx0XBjxbKVs0mpD+TWR2n5bO4qj01Y8TNRSdSqZk4Mn+OLMdEoxQevnpGKbGFok7+tD3ADV34AtmMEHDy54f4lgjdvU4jaTRI4bROVDfSA5sJ+K36zD8THUbs/loooLf6NIzbGBFhMpvqZr51GkKZqfKZlhZHlK+2QKBgEyQ6sZKOjW1wMuAFZSBKMMP1RgP3A+46EhIsbmcM6wCHUTidVixNj9cxnTobpvWLJRogSszyn5hx2afe8FGDNCUZXowbdoEEU+GEjk9Ca2dVYDvBKv/AsmyKWuTv8OVmIvolz0am4G41WCbD8ttz1mtDMYT8SMBEvKIgLHypNTLAoGALm7z5/k/NqPIWh7Mq8A6AwmMAgDp47MqMOuYBAdzFh2Z+OXh3WmGK2eO/FGT23ajG8f8CmeuVVxhdLwERMeywbgJxu9HeWWGWb798Bo8zTej3zUXZmyrnGVnrwJem/TKTCtWp6GUKC4H08pJGiV/bWJG9yVC9xD4gVSWdr3jqCkCgYBKdgAVUCsvPzNwecFt+6Msy1KipokxmK3H2WDsBGI32qS/+fI8ghvg/XMeTT4qpArnWOHhqvyWerwbKe3BZl3SDtbZvDDliQJGdIFxnC+7XzSCbEKPNN0qNObBH+1EpWNs+8i0Py/MHbM3YVqZPsNxc8UQfnDBsugWS19X8srr/Q==
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhkpd4HNoGNWrrGBYuPRaf24QwUPb667jW/rQ+WPbs3jZaDnBU79RRiQIjr7HBV4UI+JhPePWeW5J9d4r+1hTK98yJ9t3eSRR75PtQxmU1V1PG0ZVd1tks+cwPJVGGDb3EF4HMmPGIWm5L2AlbqDvqQPcRrabEB/TSxAWHCbJQiq49Aya0KIxfc51oP5GYKqvJJ9Fb7qnPDdl47SvdbjPOvXmUQ4CnGoO/2jOGLFLo1nc+XZwDd0flm/wZMjuKqgd7DXIY/Ut5mACTXyP5wbbJaA3VfkJH2MKfw2E2oVswimMnpy65U6qV05BcAqZbDBTdNU+q6pTb+WtmxWQkii1HwIDAQAB
  server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  charset: UTF-8
  sign-type: RSA2
  format: json
  # 支付成功后的异步回调地址（需内网穿透），必须是你后端的接口路径
  notify-url: https://reset-overstock-recliner.ngrok-free.dev/api/alipay/notify
  # 支付成功后的前端页面跳转地址（改成你本地前端的订单页地址）
  return-url: http://localhost:3000/order/customeorderlist

server:
  port: 8080
